name: Github Action No. 2

on:
  push:
    bramches: ["main"]

  jobs:
    build:
    runs-on: ubuntu-latest
    steps:
     -name: Checkout
      uses: actions/checkout@v3
      -name: Setp Node
      uses: actions/setup-node@v3
      with:
      node-version: "16"
     -name: Install Dependencies
      run: npm ci
     -name: Build Project
     run: npm run build  